### Générations des infos employes

In [1]:
# importation de package necessaire
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import bcrypt
import random
import string
from unidecode import unidecode
import warnings 
warnings.filterwarnings("ignore")

### Quelques définition de fonctions utiles pour la suite

In [2]:
def email_generation(first_name, surname):
    number=''
    first_name = unidecode(first_name.replace(" ","").lower())
    surname = unidecode(surname.replace(" ","").lower())
    with_digit=random.choice('012')
    if(with_digit == '0') :
        number = ''
    if(with_digit == '1') : 
        number = random.choice("0123456789")
    if(with_digit == '2') : 
        number = random.choice("0123456789") 
        number=number+random.choice("0123456789") 
        
    email = first_name+surname+number+"@gmail.com"
    return email

def random_number(number_of_digit):
    number=''
    for i in range(number_of_digit):
        number = number + random.choice("0123456789")
    return number

def phone_number_generation():
    phone_number = "+221" + random.choice(["77","78"]) + random_number(3) + random_number(2) + random_number(2)  
    return phone_number

### Algo pour la génération des données Employees

In [3]:
lst_columns = ["Emp_Id", "Store_ID", "Emp_firstname", "Emp_lastname", "Emp_email", "Emp_address", "Emp_title", "Emp_phone_number", "Emp_hire_date", "Manager_id", "Emp_status"]
df_employee = pd.DataFrame(columns = lst_columns )
# quelques liste de prénoms féminin, prénoms masculin, noms de familles sn
surname = ["Pouye", "Dia", "Sall", "Ngom", "Balde", "Cisse", "Keita", "Thiaw", "Mendy", "Sagna", "Coly", "Mballo","Badji", "Diakhaté", "Tall", "Mbaye", "Dieng", "Ka", "Ndiaye", "Sarr", "Touré", "Diouf", "Diop", "Seck", "Bambey", "Sow", "Kebe"]
first_name_f = ["Fatou","Aïssatou", "Ndèye", "Mariama", "Khady", "Sokhna", "Astou","Bineta"]
first_name_m = ["Mamadou", "Cheikh", "Ousmane", "Abdoulaye", "Samba", "Moussa", "Alioune", "Babacar", "Abdoul", "Pape", "Moustapha", "Abdourahmane", "Amadou", "Idrissa", "Serigne", "Ibrahima", "Oumar", "Aboubacar", "Assane"]
first_name = [] 
first_name.extend(first_name_f)
first_name.extend(first_name_m)

for i in range(1,len(first_name)+1):
    dic_employee = {}
    dic_employee["Emp_Id"] = f"Emp{i:03d}"
    dic_employee["Emp_firstname"] = first_name[i-1]
    dic_employee["Emp_lastname"] = surname[i-1]
    dic_employee["Emp_email"] = email_generation(dic_employee["Emp_firstname"], dic_employee["Emp_lastname"])
    dic_employee["Emp_address"] = ""
    if( i <=5 and i>=1): 
        dic_employee["Emp_title"] = "Manager" # les cinq premiers employés sont mes manqgers
    else:
        dic_employee["Emp_title"] = "Delivery Person" # les livreurs
        
    dic_employee["Emp_phone_number"] = phone_number_generation()
    dic_employee["Emp_hire_date"] = ""
    if ( i<=5 and i>=1):
        dic_employee["Manager_id"] =  ""
        dic_employee["Store_ID"] = f"Store{i:03d}"
    if(i>=6 and i<=10):
        dic_employee["Manager_id"] =  f"Emp{1:03d}"
        dic_employee["Store_ID"] = f"Store{1:03d}"
    if(i>=11 and i<=13):
        dic_employee["Manager_id"] =  f"Emp{2:03d}"
        dic_employee["Store_ID"] = f"Store{2:03d}"
    if(i>=14 and i<=19):
        dic_employee["Manager_id"] =  f"Emp{3:03d}"
        dic_employee["Store_ID"] = f"Store{3:03d}"
    if(i>=20 and i<=23):
        dic_employee["Manager_id"] =  f"Emp{4:03d}"
        dic_employee["Store_ID"] = f"Store{4:03d}"
    if(i>=24 and i<=27):
        dic_employee["Manager_id"] =  f"Emp{5:03d}" 
        dic_employee["Store_ID"] = f"Store{5:03d}"
    
    dic_employee["Emp_status"] = "activated"
    # j'ordonne les clés de mon dictionnaire pour qu'ils soient dans le meme ordre que les noms des colonnes de ma table employees
    dic_employee_sorted = {cle: dic_employee[cle] for cle in lst_columns}
    # enregistrement dans mon data frame
    df_employee = df_employee.append(dic_employee_sorted, ignore_index=True)

# chargement dans un dataset
employee_csv = df_employee.to_csv('dataset\employees.csv', encoding='utf-8-sig', index=False)

In [4]:
df_employee

,Emp_Id,Store_ID,Emp_firstname,Emp_lastname,Emp_email,Emp_address,Emp_title,Emp_phone_number,Emp_hire_date,Manager_id,Emp_status
0,Emp001,Store001,Fatou,Pouye,fatoupouye55@gmail.com,,Manager,+221775717736,,,activated
1,Emp002,Store002,Aïssatou,Dia,aissatoudia@gmail.com,,Manager,+221787171146,,,activated
2,Emp003,Store003,Ndèye,Sall,ndeyesall@gmail.com,,Manager,+221772503539,,,activated
3,Emp004,Store004,Mariama,Ngom,mariamangom@gmail.com,,Manager,+221777557439,,,activated
4,Emp005,Store005,Khady,Balde,khadybalde34@gmail.com,,Manager,+221788333096,,,activated
5,Emp006,Store001,Sokhna,Cisse,sokhnacisse8@gmail.com,,Delivery Person,+221772887635,,Emp001,activated
6,Emp007,Store001,Astou,Keita,astoukeita0@gmail.com,,Delivery Person,+221783189780,,Emp001,activated
7,Emp008,Store001,Bineta,Thiaw,binetathiaw02@gmail.com,,Delivery Person,+221770668848,,Emp001,activated
8,Emp009,Store001,Mamadou,Mendy,mamadoumendy58@gmail.com,,Delivery Person,+221771150892,,Emp001,activated
9,Emp010,Store001,Cheikh,Sagna,cheikhsagna31@gmail.com,,Delivery Person,+221784617577,,Emp001,activated
10,Emp011,Store002,Ousmane,Coly,ousmanecoly2@gmail.com,,Delivery Person,+221775921263,,Emp002,activated
11,Emp012,Store002,Abdoulaye,Mballo,abdoulayemballo07@gmail.com,,Delivery Person,+221777617268,,Emp002,activated
12,Emp013,Store002,Samba,Badji,sambabadji1@gmail.com,,Delivery Person,+221773487660,,Emp002,activated
13,Emp014,Store003,Moussa,Diakhaté,moussadiakhate@gmail.com,,Delivery Person,+221775458008,,Emp003,activated
14,Emp015,Store003,Alioune,Tall,aliounetall22@gmail.com,,Delivery Person,+221772137132,,Emp003,activated
15,Emp016,Store003,Babacar,Mbaye,babacarmbaye15@gmail.com,,Delivery Person,+221787776971,,Emp003,activated
16,Emp017,Store003,Abdoul,Dieng,abdouldieng4@gmail.com,,Delivery Person,+221788270748,,Emp003,activated
17,Emp018,Store003,Pape,Ka,papeka@gmail.com,,Delivery Person,+221771714086,,Emp003,activated
18,Emp019,Store003,Moustapha,Ndiaye,moustaphandiaye34@gmail.com,,Delivery Person,+221786643015,,Emp003,activated
19,Emp020,Store004,Abdourahmane,Sarr,abdourahmanesarr3@gmail.com,,Delivery Person,+221780966622,,Emp004,activated
20,Emp021,Store004,Amadou,Touré,amadoutoure@gmail.com,,Delivery Person,+221777939541,,Emp004,activated
21,Emp022,Store004,Idrissa,Diouf,idrissadiouf3@gmail.com,,Delivery Person,+221779702333,,Emp004,activated
22,Emp023,Store004,Serigne,Diop,serignediop@gmail.com,,Delivery Person,+221784559156,,Emp004,activated
23,Emp024,Store005,Ibrahima,Seck,ibrahimaseck@gmail.com,,Delivery Person,+221774955083,,Emp005,activated
24,Emp025,Store005,Oumar,Bambey,oumarbambey@gmail.com,,Delivery Person,+221786787558,,Emp005,activated
25,Emp026,Store005,Aboubacar,Sow,aboubacarsow22@gmail.com,,Delivery Person,+221782818473,,Emp005,activated
26,Emp027,Store005,Assane,Kebe,assanekebe48@gmail.com,,Delivery Person,+221782554338,,Emp005,activated

In [5]:
len(df_employee)

27