### Génération des données pour le dataset Shipping_cost

In [1]:
# importation de package necessaire
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import bcrypt
import random
import string
from unidecode import unidecode
import warnings 
warnings.filterwarnings("ignore")

In [2]:
### Entrons dans la génération de notre

In [3]:
# les départements avec les districts où nous livrons
department_district =  {"Dakar" : ["GUEULE TAPEE FASS COLOBANE", "FANN POINT E AMITIE", "GOREE", "MEDINA", "Plateau", "CAMBERENE" , "DIEUPPEUL DERKLE", "BISCUITERIE" , "HLM", "HANN BEL AIR", "Grand Dakar", "SICAP LIBERTE", "YOFF", "Mermoz Sacre coeur", "NGOR", "Ouakam", "Grand YOFF", "Parcelles Assainies", "Patte d'oie"],
 "Guédiawaye" : ["GOLF SUD", "MEDINA GOUNASS", "NDIAREME", "SAM NOTAIRE", "WAKHINANE NIMZAT"],
 "Pikine" : ["DALIFORT", "DJIDA THIAROYE KAO", "GUINAW RAIL NORD", "GUINAW RAIL SUD", "Pikine EST", "Pikine NORD", "Pikine OUEST", "KEUR MASSAR", "MALIKA", "YEUMBEUL NORD", "YEUMBEUL SUD", "MBAO", "DIAMAGUENE SICAP MBAO", "THIAROYE GARE", "THIAROYE SUR MER", "TIVAVOUANE DIAKSAO"],
 "Rufisque" : ["RUFISQUE EST", "RUFISQUE NORD", "RUFISQUE OUEST", "BAMBYLOR", "TIVAOUANE PEULH - NIAGA", "YENE", "BARGNY", "DIAMNIADIO", "JAXAAY-PLLES-NIAKOUL RAB", "SANGALKAM", "SEBIKOTANE", "SENDOU"],
 "GUINGUINEO" : ["DARA MBOSS", "KHELCOM BIRAME", "MBADAKHOUNE", "NDIAGO", "NGAGNICK", "NGATHIE NAOUDE", "NGELLOU", "OUROUR", "PANAL WOLOF"],
 "KAOLACK" :  ["DYA", "KEUR BAKA", "KEUR SOCE", "LATMINGUE", "NDIAFFATE", "NDIEBEL", "NDIEDIENG", "THIARE", "THIOMBY"], 
 "MBOUR" : ["DIASS", "FISSEL", "MALICOUNDA", "NDIAGANIAO", "NGUENIENE", "SANDIARA", "SESSENE", "SINDIA"],
 "THIÈS" : ["DIENDER GUEDJI", "FANDENE", "KEUR MOUSSA", "NDIEYENE SIRAKH", "NGOUNDIANE", "NOTTO", "TASSETTE", "THIENABA", "TOUBA TOUL"],
 "BIGNONA" : ["BALINGORE", "COUBALAN", "DIEGOUNE", "DJIBIDIONE", "DJINAKI", "KAFOUNTINE", "KARTIACK", "KATABA 1", "MANGAGOULACK", "MLOMP", "NIAMONE", "OULAMPANE", "OUONCK", "SINDIAN", "SUEL", "TENGHORI"],
 "ZIGUINCHOR" : ["ADEANE", "BOUTOUPA CAMARACOUND", "ENAMPOR", "NIAGUIS", "NIASSIA"]
}
districts = [] # contiendra tous les districts où nous livrons
delivery_fee = [] # contiendra les dictionnaires avec les clés correspondant aux attributs de la table shipping_cost_delivery
fees = [2000, 3000] # nos frais de livraison

for cle in department_district:
    districts.extend(department_district[cle])

for i in range(1,len(districts)+1):
    dic_fee = {}
    Delivery_fee_standard = random.choice(fees)
    dic_fee["Shipping_cost_ID"] = f"Fee_{i:03d}"
    dic_fee["District"] = (districts[i-1]).title()
    dic_fee["Delivery_fee_standard"] = Delivery_fee_standard
    dic_fee["Delivery_fee_express"] = int(Delivery_fee_standard*1.5)
    dic_fee["Delivery_status"] ="activated"
    delivery_fee.append(dic_fee)
    
# enregistrement dans un dataframe
lst_columns = ["Shipping_cost_ID", "District", "Delivery_fee_standard", "Delivery_fee_express", "Delivery_status"]
df_Shipping_cost = pd.DataFrame(columns=lst_columns)
for fee in delivery_fee:
    df_Shipping_cost = df_Shipping_cost.append(fee, ignore_index=True)

# enregistrement dans un fichier csv
shipping_cost_csv = df_Shipping_cost.to_csv('dataset\shipping_cost.csv', encoding='utf-8-sig', index=False)

In [4]:
# Affichage du dataframe df_Shipping_cost
df_Shipping_cost

,Shipping_cost_ID,District,Delivery_fee_standard,Delivery_fee_express,Delivery_status
0,Fee_001,Gueule Tapee Fass Colobane,3000,4500,activated
1,Fee_002,Fann Point E Amitie,3000,4500,activated
2,Fee_003,Goree,2000,3000,activated
3,Fee_004,Medina,3000,4500,activated
4,Fee_005,Plateau,2000,3000,activated
...,...,...,...,...,...
103,Fee_104,Adeane,3000,4500,activated
104,Fee_105,Boutoupa Camaracound,3000,4500,activated
105,Fee_106,Enampor,2000,3000,activated
106,Fee_107,Niaguis,3000,4500,activated
107,Fee_108,Niassia,3000,4500,activated